		<center>
		<button id = "shift-left" type = "button"><< Left Shift</button>
		<table class = "caesar-app" id = "caesar-table">
			<thead>
				<tr>
					<td>Alphabet:</td>
					<td>A</td>
					<td>B</td>
					<td>C</td>
					<td>D</td>
					<td>E</td>
					<td>F</td>
					<td>G</td>
					<td>H</td>
					<td>I</td>
					<td>J</td>
					<td>K</td>
					<td>L</td>
					<td>M</td>
					<td>N</td>
					<td>O</td>
					<td>P</td>
					<td>Q</td>
					<td>R</td>
					<td>S</td>
					<td>T</td>
					<td>U</td>
					<td>V</td>
					<td>W</td>
					<td>X</td>
					<td>Y</td>
					<td>Z</td>
				</tr>
			</thead>
			<tbody>
				<tr id = "cipher-char">
					<td>Cipher:</td>
					<td>A</td>
					<td>B</td>
					<td>C</td>
					<td>D</td>
					<td>E</td>
					<td>F</td>
					<td>G</td>
					<td>H</td>
					<td>I</td>
					<td>J</td>
					<td>K</td>
					<td>L</td>
					<td>M</td>
					<td>N</td>
					<td>O</td>
					<td>P</td>
					<td>Q</td>
					<td>R</td>
					<td>S</td>
					<td>T</td>
					<td>U</td>
					<td>V</td>
					<td>W</td>
					<td>X</td>
					<td>Y</td>
					<td>Z</td>
				</tr>
			</tbody>
		</table>
		<button id = "shift-right" type = "button">Right Shift>></button>
		</center>